# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - staging
  - dev

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: yarn install
  - script: npx lerna bootstrap
  - script: npx lerna run build
